// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package database

import (
	"context"
)

const checkShortNameExists = `-- name: CheckShortNameExists :one
SELECT COUNT(*) > 0 as exists
FROM links
WHERE short_name = $1 AND id != COALESCE($2, -1)
`

type CheckShortNameExistsParams struct {
	ShortName string `json:"short_name"`
	ID        int32  `json:"id"`
}

func (q *Queries) CheckShortNameExists(ctx context.Context, arg CheckShortNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkShortNameExists, arg.ShortName, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*) as total FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name)
VALUES ($1, $2)
RETURNING id, original_url, short_name, created_at
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const getAllLinks = `-- name: GetAllLinks :many
SELECT id, original_url, short_name, created_at
FROM links
ORDER BY created_at DESC
`

func (q *Queries) GetAllLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int32) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE short_name = $1
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinksWithPagination = `-- name: GetLinksWithPagination :many
SELECT id, original_url, short_name, created_at
FROM links
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLinksWithPaginationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLinksWithPagination(ctx context.Context, arg GetLinksWithPaginationParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinksWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = $2, short_name = $3
WHERE id = $1
RETURNING id, original_url, short_name, created_at
`

type UpdateLinkParams struct {
	ID          int32  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}
