// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CheckShortNameExists(ctx context.Context, arg CheckShortNameExistsParams) (bool, error)
	CountLinkVisits(ctx context.Context) (int64, error)
	CountLinks(ctx context.Context) (int64, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error)
	DeleteLink(ctx context.Context, id int32) error
	GetAllLinkVisits(ctx context.Context) ([]LinkVisit, error)
	GetAllLinks(ctx context.Context) ([]Link, error)
	GetLinkByID(ctx context.Context, id int32) (Link, error)
	GetLinkByShortName(ctx context.Context, shortName string) (Link, error)
	GetLinkVisitByID(ctx context.Context, id int32) (LinkVisit, error)
	GetLinkVisitsWithPagination(ctx context.Context, arg GetLinkVisitsWithPaginationParams) ([]LinkVisit, error)
	GetLinksWithPagination(ctx context.Context, arg GetLinksWithPaginationParams) ([]Link, error)
	GetVisitsByLinkID(ctx context.Context, linkID int32) ([]LinkVisit, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
