package main

import (
	"bytes"
	generated "code/db/generated"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/lib/pq"
	"github.com/stretchr/testify/assert"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

var db *pgxpool.Pool
var router *gin.Engine

func TestMain(m *testing.M) {
	ctx := context.Background()
	// запуск контейнера PostgreSQL
	req := testcontainers.ContainerRequest{
		Image:        "postgres:16-alpine",
		ExposedPorts: []string{"5432/tcp"},
		Env: map[string]string{
			"POSTGRES_DB":       "testdb",
			"POSTGRES_USER":     "test",
			"POSTGRES_PASSWORD": "secret",
		},
		WaitingFor: wait.ForExposedPort().WithStartupTimeout(60 * time.Second),
	}
	pgCont, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		log.Fatalf("failed to start container: %v", err)
	}
	defer pgCont.Terminate(ctx)
	// получаем адрес и порт
	mappedPort, _ := pgCont.MappedPort(ctx, "5432")
	host, _ := pgCont.Host(ctx)
	// подключение к БД
	dsn := fmt.Sprintf("postgres://test:secret@%s:%s/testdb?sslmode=disable", host, mappedPort.Port())
	db, err = pgxpool.New(context.Background(), dsn)
	if err != nil {
		log.Fatalf("failed to connect to db: %v", err)
	}
	defer db.Close()
	// применение миграций
	_, err = db.Exec(ctx, `CREATE TABLE IF NOT EXISTS links (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, original_url TEXT, short_name TEXT UNIQUE, short_url TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);`)
	if err != nil {
		log.Fatalf("failed to create table: %v", err)
	}
	// инициализация Gin
	queries := generated.New(db)
	gin.SetMode(gin.TestMode)
	router = setupRouter()
	// регистрация маршрутов
	router.GET("/api/links", listLinks(queries))
	router.GET("api/links/:id", getLinkFromId(queries))
	router.POST("api/links", createLink(queries))
	router.PUT("api/links/:id", updateLink(queries))
	router.DELETE("api/links/:id", deleteLink(queries))
	os.Exit(m.Run())
}

func TestPingRouteTableDriven(t *testing.T) {
	tests := []struct {
		name     string
		method   string
		path     string
		wantCode int
		wantBody string
	}{
		{"ping endpoint", "GET", "/ping", 200, `{"message":"pong"}`},
		{"not found", "GET", "/nonexistent", 404, ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			w := httptest.NewRecorder()
			req, _ := http.NewRequest(tt.method, tt.path, nil)
			router.ServeHTTP(w, req)

			assert.Equal(t, tt.wantCode, w.Code)
			if tt.wantBody != "" {
				assert.Equal(t, tt.wantBody, w.Body.String())
			}
		})
	}
}

func TestGetLinks(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url1', 'exmpl1'), ('https://example.com/long-url2', 'exmpl2')")
	assert.NoError(t, err)

	// выполнение запроса
	req, _ := http.NewRequest(http.MethodGet, "/api/links", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusOK, w.Code)
	var response []map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	assert.NoError(t, err)
	assert.Equal(t, 2, len(response))
}

func TestGetLinkFromIDRight(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url3', 'exmpl3'), ('https://example.com/long-url4', 'exmpl4')")
	assert.NoError(t, err)

	// выполнение запроса
	req, _ := http.NewRequest(http.MethodGet, "/api/links/2", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	want := map[string]any{"id": float64(2), "original_url": "https://example.com/long-url4", "short_name": "exmpl4", "short_url": nil}
	assert.NoError(t, err)
	assert.Equal(t, want, response)
}

func TestGetLinkFromIDWrong(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url3', 'exmpl3'), ('https://example.com/long-url4', 'exmpl4')")
	assert.NoError(t, err)

	// выполнение запроса
	req, _ := http.NewRequest(http.MethodGet, "/api/links/3", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusNotFound, w.Code)
	var response map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	want := map[string]any{"error": "link not found"}
	assert.NoError(t, err)
	assert.Equal(t, want, response)
}

func TestUpdateLink(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url3', 'exmpl3'), ('https://example.com/long-url4', 'exmpl4')")
	assert.NoError(t, err)

	// подготовка данных
	origUrl := pgtype.Text{String: "https://example.com/update_test", Valid: true}
	shortUrl := pgtype.Text{String: "exmpl_update", Valid: true}
	data := generated.UpdateLinkParams{ID: 1, OriginalUrl: origUrl, ShortName: shortUrl}
	jsonData, err := json.Marshal(data)

	// выполнение запроса
	reqUpd, _ := http.NewRequest(http.MethodPut, "/api/links/1", bytes.NewBuffer(jsonData))
	wUpd := httptest.NewRecorder()
	router.ServeHTTP(wUpd, reqUpd)

	// получение обновлённой записи
	req, _ := http.NewRequest(http.MethodGet, "/api/links/1", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	want := map[string]any{"id": float64(1), "original_url": "https://example.com/update_test", "short_name": "exmpl_update", "short_url": nil}
	assert.NoError(t, err)
	assert.Equal(t, want, response)
}

func TestDeleteLinkRight(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url4', 'exmpl4'), ('https://example.com/long-url5', 'exmpl5')")
	assert.NoError(t, err)

	// выполнение запроса на удаление записи
	reqDel, _ := http.NewRequest(http.MethodDelete, "/api/links/2", nil)
	wDel := httptest.NewRecorder()
	router.ServeHTTP(wDel, reqDel)
	assert.Equal(t, http.StatusNoContent, wDel.Code)

	// выполнение запроса на получение оставшейся записи
	req, _ := http.NewRequest(http.MethodGet, "/api/links", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusOK, w.Code)
	var response []map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	assert.NoError(t, err)
	assert.Equal(t, 1, len(response))
}

func TestDeleteLinkWrong(t *testing.T) {
	ctx := context.Background()
	// очистка данных перед тестом
	_, err := db.Exec(ctx, "DELETE FROM links")
	assert.NoError(t, err)

	// добавление тестовых данных
	_, err = db.Exec(ctx, "INSERT INTO links (original_url, short_name) VALUES ('https://example.com/long-url4', 'exmpl4'), ('https://example.com/long-url5', 'exmpl5')")
	assert.NoError(t, err)

	// выполнение запроса на удаление несуществующей записи
	req, _ := http.NewRequest(http.MethodDelete, "/api/links/5", nil)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	// проверка результатов
	assert.Equal(t, http.StatusNotFound, w.Code)
	var response map[string]any
	err = json.Unmarshal(w.Body.Bytes(), &response)
	want := map[string]any{"error": "the link does not exist"}
	assert.NoError(t, err)
	assert.Equal(t, want, response)
}
